### PR TITLE
Fix indexing on get/set

### PR DESCRIPTION
**Pull request by bengolds**
The multiplication used in get/set indexes incorrectly.

### CODE REVIEW

**Comment by LesleyLai** [comment]
> The multiplication used in get/set indexes incorrectly.

I only tested with squares and did not catch that. Thank you!

**Comment by harrygr** [comment]
@LesleyLai can you do a new release that includes this fix? The one on Elm packages still has this bug 🙏

**Comment by LesleyLai** [comment]
> 
> 
> @LesleyLai can you do a new release that includes this fix? The one on Elm packages still has this bug 🙏

Sorry, totally forgot about that. Package published now.

**Comment by harrygr** [comment]
Many thanks, and thanks for a handy package!

**Pull request merged**
